import Head from 'next/head'
import Image from 'next/image'
import Navbarr from '../components/Navbarr'
import Main from '../components/Main'
import Skills from '../components/Skills'
import Contact from '../components/Contact'
import Particle from '../components/Particle'
export default function Home() {
  const particlesInit = async (main) => {
    console.log(main);
    await loadFull(main);
  };
  const particlesLoaded = (container) => {
    console.log(container);
  };
  return (
    <div>
      <Head>
        <title>Elif Güler | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
   <Navbarr/>
  <Particle></Particle>
   <Main/>
   <Skills/>
   <Contact/>
     </div>
  )}